# Generated by Django 6.1.1 on 2026-09-13 16:11

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2025/2026', max_length=16, unique=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='e.g. CSC, SE, CYB', max_length=8)),
            ],
            options={
                'ordering': ['faculty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(help_text='e.g. COMP, SCI, AGR', max_length=8, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_student_gap', models.PositiveSmallIntegerField(default=85)),
                ('weight_lecturer_pref', models.PositiveSmallIntegerField(default=90)),
                ('weight_travel_dist', models.PositiveSmallIntegerField(default=75)),
                ('weight_load_dist', models.PositiveSmallIntegerField(default=80)),
                ('friday_hard_lock', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(help_text='Order index (1..N)', unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(help_text='e.g. "08:00 - 10:00"', max_length=32)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('institutional_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('CENTRAL_ADMIN', 'Central Administrator'), ('FACULTY_ADMIN', 'Faculty Timetable Officer'), ('LECTURER', 'Academic Staff / Lecturer'), ('STUDENT', 'Undergraduate Student')], db_index=True, max_length=20)),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')], null=True)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='timetable.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='timetable.faculty')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. CSC 301', max_length=16, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credit_units', models.PositiveSmallIntegerField(default=3)),
                ('contact_hours', models.PositiveSmallIntegerField(default=2)),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100L'), (200, '200L'), (300, '300L'), (400, '400L'), (500, '500L')])),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Harmattan (1st) Semester'), (2, 'Rain (2nd) Semester')], default=1)),
                ('expected_capacity', models.PositiveIntegerField(help_text='Expected student enrollment count')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='timetable.department')),
            ],
            options={
                'ordering': ['level', 'code'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='timetable.faculty'),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VENUE_DOUBLE_BOOKED', 'Venue Double-Booked'), ('HALL_LOCKED', 'Lecture Theatre Locked / Inaccessible'), ('CAPACITY_OVERFLOW', 'Severe Capacity Overflow'), ('SCHEDULE_OVERLAP', 'Direct Schedule Overlap'), ('LECTURER_ABSENT', 'Lecturer Did Not Appear')], max_length=32)),
                ('course_code', models.CharField(max_length=16)),
                ('venue', models.CharField(max_length=64)),
                ('day', models.CharField(max_length=16)),
                ('time_slot', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=2000)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterAdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine Directive'), ('URGENT', 'Urgent Action Required')], default='ROUTINE', max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_messages', to='timetable.faculty')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=32, unique=True)),
                ('max_hours_per_week', models.PositiveSmallIntegerField(default=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='timetable.department')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'LECTURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Harmattan (1st) Semester'), (2, 'Rain (2nd) Semester')], default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / In Preparation'), ('FACULTY_APPROVED', 'Faculty Approved'), ('PUBLISHED', 'Formally Published')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='timetable.faculty')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='timetable.academicsession')),
            ],
            options={
                'ordering': ['-session', 'faculty'],
                'unique_together': {('session', 'semester', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='timetable.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='timetable.lecturer')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='timetable.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'slot__index'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='e.g. LT-AG, TWIN-A', max_length=16, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(blank=True, help_text='Null denotes a shared central university venue (e.g. Abubakar Gimba Theatre)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='timetable.faculty')),
            ],
            options={
                'ordering': ['-capacity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], null=True)),
                ('reason', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Rescheduled'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='timetable.allocation')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='timetable.lecturer')),
                ('requested_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timeslot')),
                ('requested_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='timetable.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'code')},
        ),
        migrations.CreateModel(
            name='LecturerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')])),
                ('is_available', models.BooleanField(default=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='timetable.lecturer')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot')),
            ],
            options={
                'ordering': ['lecturer', 'day_of_week', 'slot__index'],
                'unique_together': {('lecturer', 'day_of_week', 'slot')},
            },
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['timetable', 'day_of_week', 'slot'], name='alloc_tt_day_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['venue', 'day_of_week', 'slot'], name='alloc_venue_day_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['lecturer', 'day_of_week', 'slot'], name='alloc_lec_day_slot_idx'),
        ),
    ]
