# Generated by Django 6.1.1 on 2026-09-14 23:52

import timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_allocation_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=timetable.models.user_profile_pic_path),
        ),
    ]
